spring:
  application:
    name: byte-bookstore
  datasource:
    url: jdbc:mysql://localhost:3306/byte_bookstore?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
